version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/dev/sandbox
        networks:
            - app-network

    web:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        ports:
            - "80:80"
        networks:
            - app-network

#    php:
#        image: php:8.2-fpm
#        volumes:
#            - ./src:/var/www/dev/sandbox
#        networks:
#            - app-network
#
#    nginx:
#        image: nginx:latest
#        volumes:
#            - ./src:/var/www/dev/sandbox
#            - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf
#        ports:
#            - "8080:80"
#        depends_on:
#            - php
#        networks:
#            - app-network

networks:
    app-network:
        driver: bridge
